export const recipeData = [
    {
        "id": "r1",
        "title": "Creamy Garlic Parmesan Chicken",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "Tender chicken breasts smothered in a creamy garlic Parmesan sauce. Serve with pasta or mashed potatoes.",
        "delicious":true,
    },
    {
        "id": "r2",
        "title": "Spicy Mango Salsa Fish Tacos",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "Crispy fish fillets topped with a zesty mango salsa, tucked into warm tortillas for a burst of flavor.",
        "delicious":false,
    },
    {
        "id": "r3",
        "title": "Mediterranean Quinoa Salad",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "A refreshing quinoa salad with cucumbers, tomatoes, olives, and feta cheese, drizzled with a lemon vinaigrette.",
        "delicious":false,
    },
    {
        "id": "r4",
        "title": "Savory Mushroom and Thyme Galette",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "Flaky galette crust filled with sautéed mushrooms, fresh thyme, and melted Gruyère cheese.",
        "delicious":false,
    },
    {
        "id": "r5",
        "title": "Thai Coconut Curry Noodles",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "Slurp-worthy rice noodles in a creamy coconut curry broth, garnished with cilantro and lime wedges.",
        "delicious":false,
    },
    {
        "id": "r6",
        "title": "Roasted Beetroot and Goat Cheese Salad",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "Roasted beet slices over mixed greens, topped with creamy goat cheese, candied walnuts, and balsamic vinaigrette.",
        "delicious":false,
    },
    {
        "id": "r7",
        "title": "Lemon Herb Grilled Shrimp Skewers",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "Juicy shrimp marinated in a zesty lemon herb mixture, threaded onto skewers, and grilled to perfection.",
        "delicious":false,
    },
    {
        "id": "r8",
        "title": "Blueberry Almond Breakfast Smoothie",
        "priceCurrency": "DKK",
        "price": 0,
        "description": "Start your day with a nutritious blend of blueberries, almond milk, Greek yogurt, and a touch of honey.",
        "delicious":false,    
    }

]